### PR TITLE
Issue #39: Wrapper for mgcv::gamm and gamm4::gamm4.

### PR DESCRIPTION
**Pull request by ndevln**
Hi Matteo,

I implemented the wrapper for mgcv::gamm (issue #39). Since I used `lme4` with restricted cubic splines before, I started using GAMs with gamm4. This is why I also implemented a wrapper for gamm4::gamm4. Both functions follow your naming convention:

- gammV()
- gamm4V()

When using gamm or gamm4 the gam object will be saved at obj$gam. In my implementation the gam object will be moved to the root after converting it to a gamViz object. This is beneficial, because the resulting object can be summarized (`summary(obj)`) and plotted (`plot(obj)`) like every other gamViz object created by gamV or bamV.

To keep the option to use gammV as a drop in replacement for older code, I added an option named `keepGAMObj` for keeping a copy of the gamViz object under obj$gam. To my knowledge there is no way to link or point to the object root from obj$gam (as a no copy solution). Also, this would result in a possible infinite recursion. 

This implementation has 3 downsides:

1. The memory needed to save the object is nearly doubled (2x gam model).
2. There are 2 gam objects, which can be modified independently. For example using `update()` would result in 2 different gam models within the same object. 
3. The outer model for model comparisons is the mixed model. In the base implementation by Simon Wood you have to think about which model to use, since `anova(obj)` will not work. This implementation will give results without a warning. I try to mitigate this by a big warning in the help file.

I think the only way to properly solve this, is to add a new class and implement handling this class for all mgcViz functions.

A faster solution would be to delete the root gamViz object and use the same structure as used by Simon Wood in the original packages. This would be a bit more inconvenient, but would prevent the mentioned problems.

Please tell me if you like my implementation and if I should make some changes.

Greetings
Alex

### CODE REVIEW

**Comment by ndevln** [comment]
Because I use roxygen 6.1.1 every help .rd file has changes. This is why I forgot the check in the NAMESPACE file so it could export the new functions. This resulted in an CI build fail. Sry.

**Review by mfasiolo — APPROVED** [review]

**Comment by mfasiolo** [comment]
Hi Alex,

 many thanks for this! Regarding having 2 copies of a gam object within the output of gamm, I think that probably there is no memory problem because when you do:
```
obj <- do.call("getViz", c(list("o" = obj$gam), aViz))
if ( keepGAMObj ) { obj$gam <- obj }
```
obj is passed by reference in `obj$gam <- obj`. In fact if you do:

```
library(mgcViz)
# Simulate data
dat <- gamSim(1,n=1e4,scale=2) ## simulate 4 term additive truth
## Now add 20 level random effect `fac'...
dat$fac <- fac <- as.factor(sample(1:20,1e4,replace=TRUE))
dat$y <- dat$y + model.matrix(~fac-1) %*% rnorm(20) * 0.5

br <- gammV(y~s(x0)+x1+s(x2), data=dat,random=list(fac=~1), keepGAMObj = TRUE)

# Creating 1000 copies!!!!
for(ii in 1:1000){
  br[[paste0("new", ii)]] <- br$gam
}
```

The memory usage does not increase. So we might even consider removing the keepGAMObj argument
and do obj$gam <- obj by default, given that there is no memory cost. Of course the problems 2 and
3 you mention are still there.

Best,

Matteo

**Comment by mfasiolo** [comment]
Sorry, just to clarify, obj is not passed by reference but the memory savings are a consequence of lazy evaluation (or at least that's my understanding).

**Comment by ndevln** [comment]
Yes you are right. I tried to take advantage of lazy evaluation, but my code still sometimes results in an increased memory usage. As far as I know there is no function in R to control this inconsistent behaviour (except writing C code?). There was a way using [.Alias](https://www.math.ucla.edu/~anderson/rw1001/library/base/html/zAlias.html), but this function is deprecated. .Alias implemented C style pointer functionality.

But I'm happy you like it :)

**Pull request merged**
