### PR TITLE
Change Legend labeling for mqgam smooth plots and fix #53

### LINKED ISSUE #53: Correct x-axis label in plot.mgamViz factor plots
When plotting a factor effect on multiple models, the xlabel should indicate the model ID but it currently reports the name of the factor variable.

### PR DESCRIPTION
**Pull request by ndevln**
Hello Matteo,

this pull request is a change in the legend of mqgam smooth plots. In the current state it is really hard to deduce the quantiles used for calculation from the figure. I change the legend to explicitly state them. The color scale (default ggplot blue) is unchanged. But there are 2 options. The version I picked is in my opinion the clearer option (first figure). The second figure keeps the colorbar, but the ticks are only rendered for used quantiles. (This is controlled by deleting Line 50 in plot_multi_mgcv_smooth_1D.R)

I also fixed issue #53 and added the new legend to asFact=F. The third figure is the version I choose for this pull request. I prefer the 4th figure, because the color of the bigger points is easier to see. Again the last version is keeping the colorbar (5th fig.).

The strange errorbar width is created in L_ciBar.R at Line 44. 
`if( is.null(a$width) ){ a$width <- 0.5 }`
Inside this function I can't see if the x-axis is discrete or continuous. Also, I'm not sure where this function is called, when plotting with plot.mgamViz.

Please tell me which version you prefer and I will change the code accordingly. My test script is at the end. 

Greetings
Alex

1.
smooth_discrete_legend
2.
smooth_colorbar
3.
factor_points_normal
4.
factor_point_big
5.
factor_colorbar

```
library(mgcViz)
dat <- gamSim(4, n=300, dist="normal", scale=2)

fit <- mqgamV(y~ fac + s(x1), data=dat, err = 0.05, qu = c(0.2, 0.8, 0.5))

plot(fit, select=1)
plot(fit, select=2, asFact=T)
plot(fit, select=2, asFact=F)
```

### CODE REVIEW

**Comment by mfasiolo** [comment]
Hi Alex,

 good job on #53 ! As you say, I think that the first legend version is clearer, but it could become cumbersome if the number of quantiles is large (say > 10). Maybe the best thing to do is to use the first type of legend for n < 10 quantiles, and the colourbar for n > 10 (but with p < n ticks)? Then we could add the asFact argument also to plot.multi.mgcv.smooth.1D so that users can overwrite the default.

Regarding this:
`if( is.null(a$width) ){ a$width <- 0.5 }`
I just realized that this makes sense only if asFact = TRUE (otherwise the bars are too wide and overlap, as in your plots above). To see where the default layers are added you should look at print_gamViz.R.
Anyway, if you deal with your code for #53 and the legend, I will then try to deal with this width problem. 

Best,

Matteo

**Comment by ndevln** [comment]
Hi Matteo,

`plot.multi.mgcv.smooth.1D` now has an `asFact` option. This option decides if a factor legend or a colour bar legend will be plotted. If this option is not set, then it will default to `TRUE` for n<10, else it will be `FALSE`. The colour bar ticks will be plotted if they are at least 0.1 apart. This gave better results than fixing the number of ticks, because labels only 0.05 apart did overlap. If the ticks are too close together, ggplot2 default ticks will be used. 

This behaviour is consistent for `plot.multi.ptermFactor`. `asFact=FALSE` always results in a colour bar legend. Also, the tick behaviour is the same. As before `plot.multi.ptermFactor` `asFact `will always default to `TRUE`.

I also updated the documentation.

Best,
Alex

```
dat <- gamSim(4, n=300, dist="normal", scale=2)

fit <- mqgamV(y ~ fac + s(x1), data=dat, err = 0.05, qu = c(0.1,0.15,0.5,0.8,0.85,0.9))
fit <- mqgamV(y ~ fac + s(x1), data=dat, err = 0.05, qu = c(1:9/10))
fit <- mqgamV(y ~ fac + s(x1), data=dat, err = 0.05, qu = c(1:10/10 - 0.05))
fit <- mqgamV(y ~ fac + s(x1), data=dat, err = 0.05, qu = c(1:11/12))


plot(fit, select=1)
plot(fit, select=1, asFact=F)
plot(fit, select=1, asFact=T)
plot(fit, select=2, asFact=T)
plot(fit, select=2, asFact=F)
```

**Comment by mfasiolo** [comment]
Hi Alex,

 great job, now I will merge and then I'll have a look at whether this still works:

https://mfasiolo.github.io/mgcViz/articles/miscellanea.html

that is, plot.mgamViz should work also for lists of gams() (not only for multiple quantile GAMs).

Best,

Matteo

**Comment by mfasiolo** [comment]
Ok this a9fe80743ce890ba12c23dad55115aff55a85b7b should make so that `asFact` and related code is used only when we are dealing with the output of mqgamV.

**Pull request merged**
